# Generated by Django 2.2.6 on 2019-10-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0002_auto_20191013_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='standup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standups', to='standup.StandupEvent'),
        ),
    ]
