# Generated by Django 2.2.6 on 2019-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0003_auto_20191013_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='discord_channel_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='discord_guild_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='standup',
            name='pinned_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standupparticipationanswer',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='standup.StandupParticipation'),
        ),
    ]
