# Generated by Django 2.2.6 on 2019-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0004_auto_20191015_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='standup',
            name='rebuild_message',
            field=models.BooleanField(default=False),
        ),
    ]
