# Generated by Django 2.2.6 on 2019-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0006_auto_20191015_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
