# Generated by Django 2.2.6 on 2019-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0007_auto_20191015_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='standuptype',
            name='private',
            field=models.BooleanField(default=False, help_text='If enabled only participants of the standup can view the standup, the public URL will be disabled!'),
        ),
    ]
