# Generated by Django 2.2.6 on 2019-10-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0008_auto_20191017_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupquestion',
            name='important',
            field=models.BooleanField(default=False, help_text='Will mark this answer as extra obvious if it is filled in'),
        ),
    ]
