# Generated by Django 2.2.6 on 2019-10-18 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0009_standupquestion_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupquestion',
            name='prefill_last_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_prefill', to='standup.StandupQuestion'),
        ),
    ]
