# Generated by Django 2.2.6 on 2019-10-30 21:04

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0010_standupquestion_prefill_last_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Amsterdam'),
        ),
    ]
