# Generated by Django 2.2.6 on 2019-11-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0011_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standupparticipation',
            name='read_only',
            field=models.BooleanField(default=False),
        ),
    ]
