# Generated by Django 2.2.6 on 2019-11-16 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0013_standup_standup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='standuptype',
            name='public_publish_after',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=28800)),
        ),
    ]
