# Generated by Django 2.2.6 on 2019-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0015_user_mute_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='standuptype',
            name='publish_to_channel',
            field=models.BooleanField(default=False, help_text="publish to the channel even if it's a private standup"),
        ),
    ]
