# Generated by Django 2.2.6 on 2020-01-24 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0016_standuptype_publish_to_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupparticipation',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='standuptype',
            name='public_publish_after',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
