# Generated by Django 2.2.6 on 2020-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0017_auto_20200124_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='standuptype',
            name='minimum_days_between_standups',
            field=models.IntegerField(default=0),
        ),
    ]
